

export const NATIONALITIES = [
  // A
  { value: "AFGHANE", label: "Afghane" },
  { value: "SUD_AFRICAINE", label: "Sud-Africaine" },
  { value: "ALBANAISE", label: "Albanaise" },
  { value: "ALGERIENNE", label: "Algérienne" },
  { value: "ALLEMANDE", label: "Allemande" },
  { value: "AMERICAINE", label: "Américaine" },
  { value: "ANDORRANE", label: "Andorrane" },
  { value: "ANGOLAISE", label: "Angolaise" },
  { value: "ANTIGUAISE_ET_BARBUDIENNE", label: "Antiguaise et Barbudienne" },
  { value: "SAOUDIENNE", label: "Saoudienne" },
  { value: "ARGENTINE", label: "Argentine" },
  { value: "ARMENIENNE", label: "Arménienne" },
  { value: "AUSTRALIENNE", label: "Australienne" },
  { value: "AUTRICHIENNE", label: "Autrichienne" },
  { value: "AZERBAIDJANAISE", label: "Azerbaïdjanaise" },

  // B
  { value: "BAHAMIENNE", label: "Bahamienne" },
  { value: "BAHREINIENNE", label: "Bahreïnienne" },
  { value: "BANGLADAISE", label: "Bangladaise" },
  { value: "BARBADIENNE", label: "Barbadienne" },
  { value: "BELGE", label: "Belge" },
  { value: "BELIZIENNE", label: "Bélizienne" },
  { value: "BENINOISE", label: "Béninoise" },
  { value: "BHOUTANAISE", label: "Bhoutanaise" },
  { value: "BIELORUSSE", label: "Biélorusse" },
  { value: "BIRMANE", label: "Birmane" },
  { value: "BOLIVIENNE", label: "Bolivienne" },
  { value: "BOSNIENNE", label: "Bosnienne" },
  { value: "BOTSWANAISE", label: "Botswanaise" },
  { value: "BRESILIENNE", label: "Brésilienne" },
  { value: "BRUNEIENNE", label: "Brunéienne" },
  { value: "BULGARE", label: "Bulgare" },
  { value: "BURKINABE", label: "Burkinabè" },
  { value: "BURUNDAISE", label: "Burundaise" },

  // C
  { value: "CAMBODGIENNE", label: "Cambodgienne" },
  { value: "CAMEROUNAISE", label: "Camerounaise" },
  { value: "CANADIENNE", label: "Canadienne" },
  { value: "CAP_VERDIENNE", label: "Cap-Verdienne" },
  { value: "CENTRAFRICAINE", label: "Centrafricaine" },
  { value: "CHILIENNE", label: "Chilienne" },
  { value: "CHINOISE", label: "Chinoise" },
  { value: "CHYPRIOTE", label: "Chypriote" },
  { value: "COLOMBIENNE", label: "Colombienne" },
  { value: "COMORIENNE", label: "Comorienne" },
  { value: "CONGOLAISE_BRAZZAVILLE", label: "Congolaise (Brazzaville)" },
  { value: "CONGOLAISE_RDC", label: "Congolaise (RDC)" },
  { value: "NORD_COREENNE", label: "Nord-Coréenne" },
  { value: "SUD_COREENNE", label: "Sud-Coréenne" },
  { value: "COSTA_RICAINE", label: "Costa Ricaise" },
  { value: "IVORIENNE", label: "Ivoirienne" },
  { value: "CROATE", label: "Croate" },
  { value: "CUBAINE", label: "Cubaine" },

  // D - E
  { value: "DANOISE", label: "Danoise" },
  { value: "DJIBOUTIENNE", label: "Djiboutienne" },
  { value: "DOMINICAINE", label: "Dominicaine" },
  { value: "DOMINICAINE_REP", label: "Dominicaine (République)" },
  { value: "EGYPTIENNE", label: "Égyptienne" },
  { value: "SALVADORIENNE", label: "Salvadorienne" },
  { value: "EMIRATI", label: "Émirati" },
  { value: "EQUATORIENNE", label: "Équatorienne" },
  { value: "ERYTHREEENNE", label: "Érythréenne" },
  { value: "ESPAGNOLE", label: "Espagnole" },
  { value: "ESTONIENNE", label: "Estonienne" },
  { value: "ETATS_FEDERES_DE_MICRONESIE", label: "Fédérée de Micronésie" },
  { value: "ETHIOPIENNE", label: "Éthiopienne" },

  // F - G
  { value: "FIDJIENNE", label: "Fidjienne" },
  { value: "FINLANDAISE", label: "Finlandaise" },
  { value: "FRANCAISE", label: "Française" },
  { value: "GABONAISE", label: "Gabonaise" },
  { value: "GAMBIENNE", label: "Gambienne" },
  { value: "GEORGIENNE", label: "Géorgienne" },
  { value: "GHANEENNE", label: "Ghanéenne" },
  { value: "GRECQUE", label: "Grecque" },
  { value: "GRENADIENNE", label: "Grenadienne" },
  { value: "GUATEMALTEQUE", label: "Guatémaltèque" },
  { value: "GUINEENNE", label: "Guinéenne" },
  { value: "BISSAU_GUINEENNE", label: "Bissau-Guinéenne" },
  { value: "EQUATO_GUINEENNE", label: "Équatoguinéenne" },
  { value: "GUYANAISE", label: "Guyanaise" },

  // H - I
  { value: "HAITIENNE", label: "Haïtienne" },
  { value: "HONDURIENNE", label: "Hondurienne" },
  { value: "HONGROISE", label: "Hongroise" },
  { value: "INDIENNE", label: "Indienne" },
  { value: "INDONESIENNE", label: "Indonésienne" },
  { value: "IRAKIENNE", label: "Irakienne" },
  { value: "IRANIENNE", label: "Iranienne" },
  { value: "IRLANDAISE", label: "Irlandaise" },
  { value: "ISLANDAISE", label: "Islandaise" },
  { value: "ISRAELIENNE", label: "Israélienne" },
  { value: "ITALIENNE", label: "Italienne" },

  // J - K - L
  { value: "JAMAICAINE", label: "Jamaïcaine" },
  { value: "JAPONAISE", label: "Japonaise" },
  { value: "JORDANIANNE", label: "Jordanienne" },
  { value: "KAZAKHE", label: "Kazakhe" },
  { value: "KENYANE", label: "Kenyane" },
  { value: "KIRGHIZE", label: "Kirghize" },
  { value: "KIRIBATIENNE", label: "Kiribatienne" },
  { value: "KOWEITIENNE", label: "Koweïtienne" },
  { value: "LAOTIENNE", label: "Laotienne" },
  { value: "LESOTHIENNE", label: "Lésothienne" },
  { value: "LETTONNE", label: "Lettonne" },
  { value: "LIBANAISE", label: "Libanaise" },
  { value: "LIBERIENNE", label: "Libérienne" },
  { value: "LIBYENNE", label: "Libyenne" },
  { value: "LIECHTENSTEINOISE", label: "Liechtensteinoise" },
  { value: "LITUANIENNE", label: "Lituanienne" },
  { value: "LUXEMBOURGEOISE", label: "Luxembourgeoise" },

  // M
  { value: "MACEDONIENNE_DU_NORD", label: "Macédonienne du Nord" },
  { value: "MALGACHE", label: "Malgache" },
  { value: "MALAISIENNE", label: "Malaisienne" },
  { value: "MALAWIENNE", label: "Malawienne" },
  { value: "MALDIVIENNE", label: "Maldivienne" },
  { value: "MALIENNE", label: "Malienne" },
  { value: "MALTAISE", label: "Maltaise" },
  { value: "MAROCAINE", label: "Marocaine" },
  { value: "MARSHALLAISE", label: "Marshallaise" },
  { value: "MAURICIENNE", label: "Mauricienne" },
  { value: "MAURITANIENNE", label: "Mauritanienne" },
  { value: "MEXICAINE", label: "Mexicaine" },
  { value: "MOLDAVE", label: "Moldave" },
  { value: "MONACO", label: "Monegasque" },
  { value: "MONGOLIENNE", label: "Mongolienne" },
  { value: "MONTENEGRINE", label: "Monténégrine" },
  { value: "MOZAMBICAINE", label: "Mozambicaine" },

  // N
  { value: "NAMIBIENNE", label: "Namibienne" },
  { value: "NAURUENNE", label: "Nauruane" },
  { value: "NEPALAISE", label: "Népalaise" },
  { value: "NICARAGUAYENNE", label: "Nicaraguayenne" },
  { value: "NIGERIENNE", label: "Nigérienne" },
  { value: "NIGERIANE", label: "Nigériane" },
  { value: "NORVEGIENNE", label: "Norvégienne" },
  { value: "NEO_ZELANDAISE", label: "Néo-Zélandaise" },

  // O - P
  { value: "OMANAISE", label: "Omanaise" },
  { value: "OUGANDAISE", label: "Ougandaise" },
  { value: "OUZBEKE", label: "Ouzbèke" },
  { value: "PAKISTANAISE", label: "Pakistanaise" },
  { value: "PALAOSIENNE", label: "Palaosienne" },
  { value: "PALESTINIENNE", label: "Palestinienne" },
  { value: "PANAMEENNE", label: "Panaméenne" },
  { value: "PAPOUASO_NEO_GUINEENNE", label: "Papouane-Néo-Guinéenne" },
  { value: "PARAGUAYENNE", label: "Paraguayenne" },
  { value: "PAYS_BAS", label: "Néerlandaise" },
  { value: "PERUVIENNE", label: "Péruvienne" },
  { value: "PHILIPPINES", label: "Philippine" },
  { value: "POLONAISE", label: "Polonaise" },
  { value: "PORTUGAISE", label: "Portugaise" },

  // Q - R - S
  { value: "QATARIENNE", label: "Qatarienne" },
  { value: "ROUMAINE", label: "Roumaine" },
  { value: "BRITANNIQUE", label: "Britannique (Royaume-Uni)" },
  { value: "RUSSE", label: "Russe" },
  { value: "RWANDAISE", label: "Rwandaise" },
  { value: "SAINT_KITTS_ET_NEVIS", label: "Saint-Kitts-et-Nevisienne" },
  { value: "SAINT_MARINAISE", label: "Saint-Marinaise" },
  { value: "SAINT_VINCENT_ET_GRENADINES", label: "Saint-Vincentaise et Grenadine" },
  { value: "SAINTE_LUCIENNE", label: "Sainte-Lucienne" },
  { value: "SALOMONAISE", label: "Salomonaise" },
  { value: "SAMOANE", label: "Samoane" },
  { value: "SAO_TOMEENNE", label: "Santoméenne" },
  { value: "SENEGALAISE", label: "Sénégalaise" },
  { value: "SERBE", label: "Serbe" },
  { value: "SEYCHELLOISE", label: "Seychelloise" },
  { value: "SIERRA_LEONAISE", label: "Sierra-Léonaise" },
  { value: "SINGAPOURIENNE", label: "Singapourienne" },
  { value: "SLOVAQUE", label: "Slovaque" },
  { value: "SLOVENE", label: "Slovène" },
  { value: "SOMALIENNE", label: "Somalienne" },
  { value: "SOUDANAISE", label: "Soudanaise" },
  { value: "SUD_SOUDANAISE", label: "Sud-Soudanaise" },
  { value: "SRI_LANKAISE", label: "Sri Lankaise" },
  { value: "SUEDOISE", label: "Suédoise" },
  { value: "SUISSE", label: "Suisse" },
  { value: "SURINAMAISE", label: "Surinamaise" },
  { value: "SYRIENNE", label: "Syrienne" },

  // T - U
  { value: "TADJIK", label: "Tadjik" },
  { value: "TANZANIENNE", label: "Tanzanienne" },
  { value: "TCHADIENNE", label: "Tchadienne" },
  { value: "TCHEQUE", label: "Tchèque" },
  { value: "THAILANDAISE", label: "Thaïlandaise" },
  { value: "TIMORAISE", label: "Timoraise" },
  { value: "TOGOLAISE", label: "Togolaise" },
  { value: "TONGANIENNE", label: "Tonganienne" },
  { value: "TRINIDADIENNE_ET_TOBAGIENNE", label: "Trinidadienne et Tobagienne" },
  { value: "TUNISIENNE", label: "Tunisienne" },
  { value: "TURQUE", label: "Turque" },
  { value: "TURKMENE", label: "Turkmène" },
  { value: "TUVALUANE", label: "Tuvaluane" },
  { value: "UKRAINIENNE", label: "Ukrainienne" },
  { value: "URUGUAYENNE", label: "Uruguayenne" },

  // V - W - Y - Z
  { value: "VANUATAISE", label: "Vanuataise" },
  { value: "VATICANE", label: "Vaticane" },
  { value: "VENEZUELIENNE", label: "Vénézuélienne" },
  { value: "VIETNAMIENNE", label: "Vietnamienne" },
  { value: "YEMENITE", label: "Yéménite" },
  { value: "ZAMBIENNE", label: "Zambienne" },
  { value: "ZIMBABWEENNE", label: "Zimbabwéenne" },
];