/*
  Warnings:

  - The values [NATIONAL,FOREIGN] on the enum `Nationality` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Nationality_new" AS ENUM ('AFGHANE', 'SUD_AFRICAINE', 'ALBANAISE', 'ALGERIENNE', 'ALLEMANDE', 'AMERICAINE', 'ANDORRANE', 'ANGOLAISE', 'ANTIGUAISE_ET_BARBUDIENNE', 'SAOUDIENNE', 'ARGENTINE', 'ARMENIENNE', 'AUSTRALIENNE', 'AUTRICHIENNE', 'AZERBAIDJANAISE', 'BAHAMIENNE', 'BAHREINIENNE', 'BANGLADAISE', 'BARBADIENNE', 'BELGE', 'BELIZIENNE', 'BENINOISE', 'BHOUTANAISE', 'BIELORUSSE', 'BIRMANE', 'BOLIVIENNE', 'BOSNIENNE', 'BOTSWANAISE', 'BRESILIENNE', 'BRUNEIENNE', 'BULGARE', 'BURKINABE', 'BURUNDAISE', 'CAMBODGIENNE', 'CAMEROUNAISE', 'CANADIENNE', 'CAP_VERDIENNE', 'CENTRAFRICAINE', 'CHILIENNE', 'CHINOISE', 'CHYPRIOTE', 'COLOMBIENNE', 'COMORIENNE', 'CONGOLAISE_BRAZZAVILLE', 'CONGOLAISE_RDC', 'NORD_COREENNE', 'SUD_COREENNE', 'COSTA_RICAINE', 'IVORIENNE', 'CROATE', 'CUBAINE', 'DANOISE', 'DJIBOUTIENNE', 'DOMINICAINE', 'DOMINICAINE_REP', 'EGYPTIENNE', 'SALVADORIENNE', 'EMIRATI', 'EQUATORIENNE', 'ERYTHREEENNE', 'ESPAGNOLE', 'ESTONIENNE', 'ETATS_FEDERES_DE_MICRONESIE', 'ETHIOPIENNE', 'FIDJIENNE', 'FINLANDAISE', 'FRANCAISE', 'GABONAISE', 'GAMBIENNE', 'GEORGIENNE', 'GHANEENNE', 'GRECQUE', 'GRENADIENNE', 'GUATEMALTEQUE', 'GUINEENNE', 'BISSAU_GUINEENNE', 'EQUATO_GUINEENNE', 'GUYANAISE', 'HAITIENNE', 'HONDURIENNE', 'HONGROISE', 'INDIENNE', 'INDONESIENNE', 'IRAKIENNE', 'IRANIENNE', 'IRLANDAISE', 'ISLANDAISE', 'ISRAELIENNE', 'ITALIENNE', 'JAMAICAINE', 'JAPONAISE', 'JORDANIANNE', 'KAZAKHE', 'KENYANE', 'KIRGHIZE', 'KIRIBATIENNE', 'KOWEITIENNE', 'LAOTIENNE', 'LESOTHIENNE', 'LETTONNE', 'LIBANAISE', 'LIBERIENNE', 'LIBYENNE', 'LIECHTENSTEINOISE', 'LITUANIENNE', 'LUXEMBOURGEOISE', 'MACEDONIENNE_DU_NORD', 'MALGACHE', 'MALAISIENNE', 'MALAWIENNE', 'MALDIVIENNE', 'MALIENNE', 'MALTAISE', 'MAROCAINE', 'MARSHALLAISE', 'MAURICIENNE', 'MAURITANIENNE', 'MEXICAINE', 'MOLDAVE', 'MONACO', 'MONGOLIENNE', 'MONTENEGRINE', 'MOZAMBICAINE', 'NAMIBIENNE', 'NAURUENNE', 'NEPALAISE', 'NICARAGUAYENNE', 'NIGERIENNE', 'NIGERIANE', 'NORVEGIENNE', 'NEO_ZELANDAISE', 'OMANAISE', 'OUGANDAISE', 'OUZBEKE', 'PAKISTANAISE', 'PALAOSIENNE', 'PALESTINIENNE', 'PANAMEENNE', 'PAPOUASO_NEO_GUINEENNE', 'PARAGUAYENNE', 'PAYS_BAS', 'PERUVIENNE', 'PHILIPPINES', 'POLONAISE', 'PORTUGAISE', 'QATARIENNE', 'ROUMAINE', 'BRITANNIQUE', 'RUSSE', 'RWANDAISE', 'SAINT_KITTS_ET_NEVIS', 'SAINT_MARINAISE', 'SAINT_VINCENT_ET_GRENADINES', 'SAINTE_LUCIENNE', 'SALOMONAISE', 'SAMOANE', 'SAO_TOMEENNE', 'SENEGALAISE', 'SERBE', 'SEYCHELLOISE', 'SIERRA_LEONAISE', 'SINGAPOURIENNE', 'SLOVAQUE', 'SLOVENE', 'SOMALIENNE', 'SOUDANAISE', 'SUD_SOUDANAISE', 'SRI_LANKAISE', 'SUEDOISE', 'SUISSE', 'SURINAMAISE', 'SYRIENNE', 'TADJIK', 'TANZANIENNE', 'TCHADIENNE', 'TCHEQUE', 'THAILANDAISE', 'TIMORAISE', 'TOGOLAISE', 'TONGANIENNE', 'TRINIDADIENNE_ET_TOBAGIENNE', 'TUNISIENNE', 'TURQUE', 'TURKMENE', 'TUVALUANE', 'UKRAINIENNE', 'URUGUAYENNE', 'VANUATAISE', 'VATICANE', 'VENEZUELIENNE', 'VIETNAMIENNE', 'YEMENITE', 'ZAMBIENNE', 'ZIMBABWEENNE');
ALTER TABLE "citizens" ALTER COLUMN "nationality" TYPE "Nationality_new" USING ("nationality"::text::"Nationality_new");
ALTER TYPE "Nationality" RENAME TO "Nationality_old";
ALTER TYPE "Nationality_new" RENAME TO "Nationality";
DROP TYPE "Nationality_old";
COMMIT;

-- CreateTable
CREATE TABLE "fingerprint_embeddings" (
    "id" TEXT NOT NULL,
    "citizenId" TEXT NOT NULL,
    "embedding" DOUBLE PRECISION[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "fingerprint_embeddings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "fingerprint_embeddings_citizenId_key" ON "fingerprint_embeddings"("citizenId");

-- AddForeignKey
ALTER TABLE "fingerprint_embeddings" ADD CONSTRAINT "fingerprint_embeddings_citizenId_fkey" FOREIGN KEY ("citizenId") REFERENCES "citizens"("id") ON DELETE CASCADE ON UPDATE CASCADE;
